version: 2

builds:
  - main: .
    binary: kannon
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/kannon-email/kannon/cmd.Version={{.Version}}
      - -X github.com/kannon-email/kannon/cmd.Commit={{.Commit}}
      - -X github.com/kannon-email/kannon/cmd.Date={{.Date}}

archives:
  - formats:
      - tar.gz
    files:
      - LICENSE
      - README.md
