// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: kannon/mailer/types/send.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sender struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sender) Reset() {
	*x = Sender{}
	mi := &file_kannon_mailer_types_send_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sender) ProtoMessage() {}

func (x *Sender) ProtoReflect() protoreflect.Message {
	mi := &file_kannon_mailer_types_send_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sender.ProtoReflect.Descriptor instead.
func (*Sender) Descriptor() ([]byte, []int) {
	return file_kannon_mailer_types_send_proto_rawDescGZIP(), []int{0}
}

func (x *Sender) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Sender) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type Recipient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recipient) Reset() {
	*x = Recipient{}
	mi := &file_kannon_mailer_types_send_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipient) ProtoMessage() {}

func (x *Recipient) ProtoReflect() protoreflect.Message {
	mi := &file_kannon_mailer_types_send_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipient.ProtoReflect.Descriptor instead.
func (*Recipient) Descriptor() ([]byte, []int) {
	return file_kannon_mailer_types_send_proto_rawDescGZIP(), []int{1}
}

func (x *Recipient) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Recipient) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_kannon_mailer_types_send_proto protoreflect.FileDescriptor

const file_kannon_mailer_types_send_proto_rawDesc = "" +
	"\n" +
	"\x1ekannon/mailer/types/send.proto\x12\x17pkg.kannon.mailer.types\"4\n" +
	"\x06Sender\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\"\xa4\x01\n" +
	"\tRecipient\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12F\n" +
	"\x06fields\x18\x02 \x03(\v2..pkg.kannon.mailer.types.Recipient.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\xe2\x01\n" +
	"\x1bcom.pkg.kannon.mailer.typesB\tSendProtoP\x01Z8github.com/kannon-email/kannon/proto/kannon/mailer/types\xa2\x02\x04PKMT\xaa\x02\x17Pkg.Kannon.Mailer.Types\xca\x02\x17Pkg\\Kannon\\Mailer\\Types\xe2\x02#Pkg\\Kannon\\Mailer\\Types\\GPBMetadata\xea\x02\x1aPkg::Kannon::Mailer::Typesb\x06proto3"

var (
	file_kannon_mailer_types_send_proto_rawDescOnce sync.Once
	file_kannon_mailer_types_send_proto_rawDescData []byte
)

func file_kannon_mailer_types_send_proto_rawDescGZIP() []byte {
	file_kannon_mailer_types_send_proto_rawDescOnce.Do(func() {
		file_kannon_mailer_types_send_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kannon_mailer_types_send_proto_rawDesc), len(file_kannon_mailer_types_send_proto_rawDesc)))
	})
	return file_kannon_mailer_types_send_proto_rawDescData
}

var file_kannon_mailer_types_send_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kannon_mailer_types_send_proto_goTypes = []any{
	(*Sender)(nil),    // 0: pkg.kannon.mailer.types.Sender
	(*Recipient)(nil), // 1: pkg.kannon.mailer.types.Recipient
	nil,               // 2: pkg.kannon.mailer.types.Recipient.FieldsEntry
}
var file_kannon_mailer_types_send_proto_depIdxs = []int32{
	2, // 0: pkg.kannon.mailer.types.Recipient.fields:type_name -> pkg.kannon.mailer.types.Recipient.FieldsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kannon_mailer_types_send_proto_init() }
func file_kannon_mailer_types_send_proto_init() {
	if File_kannon_mailer_types_send_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kannon_mailer_types_send_proto_rawDesc), len(file_kannon_mailer_types_send_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kannon_mailer_types_send_proto_goTypes,
		DependencyIndexes: file_kannon_mailer_types_send_proto_depIdxs,
		MessageInfos:      file_kannon_mailer_types_send_proto_msgTypes,
	}.Build()
	File_kannon_mailer_types_send_proto = out.File
	file_kannon_mailer_types_send_proto_goTypes = nil
	file_kannon_mailer_types_send_proto_depIdxs = nil
}
