// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package sq

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.insertAcceptedStmt, err = db.PrepareContext(ctx, insertAccepted); err != nil {
		return nil, fmt.Errorf("error preparing query InsertAccepted: %w", err)
	}
	if q.insertBouncedStmt, err = db.PrepareContext(ctx, insertBounced); err != nil {
		return nil, fmt.Errorf("error preparing query InsertBounced: %w", err)
	}
	if q.insertDeliveredStmt, err = db.PrepareContext(ctx, insertDelivered); err != nil {
		return nil, fmt.Errorf("error preparing query InsertDelivered: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.insertAcceptedStmt != nil {
		if cerr := q.insertAcceptedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertAcceptedStmt: %w", cerr)
		}
	}
	if q.insertBouncedStmt != nil {
		if cerr := q.insertBouncedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertBouncedStmt: %w", cerr)
		}
	}
	if q.insertDeliveredStmt != nil {
		if cerr := q.insertDeliveredStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertDeliveredStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                  DBTX
	tx                  *sql.Tx
	insertAcceptedStmt  *sql.Stmt
	insertBouncedStmt   *sql.Stmt
	insertDeliveredStmt *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                  tx,
		tx:                  tx,
		insertAcceptedStmt:  q.insertAcceptedStmt,
		insertBouncedStmt:   q.insertBouncedStmt,
		insertDeliveredStmt: q.insertDeliveredStmt,
	}
}
