// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package sq

import (
	"time"
)

type Accepted struct {
	ID        int32
	Email     string
	MessageID string
	Timestamp time.Time
}

type Bounced struct {
	ID        int32
	Email     string
	MessageID string
	ErrCode   int32
	ErrMsg    string
	Timestamp time.Time
}

type Delivered struct {
	ID        int32
	Email     string
	MessageID string
	Timestamp time.Time
}
