// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: kannon/mailer/apiv1/mailerapiv1.proto

package apiv1

import (
	types "github.com/kannon-email/kannon/proto/kannon/mailer/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_kannon_mailer_apiv1_mailerapiv1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_kannon_mailer_apiv1_mailerapiv1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_kannon_mailer_apiv1_mailerapiv1_proto_rawDescGZIP(), []int{0}
}

func (x *Attachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attachment) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type SendHTMLReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        *types.Sender          `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Html          string                 `protobuf:"bytes,4,opt,name=html,proto3" json:"html,omitempty"`
	ScheduledTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=scheduled_time,json=scheduledTime,proto3,oneof" json:"scheduled_time,omitempty"`
	Recipients    []*types.Recipient     `protobuf:"bytes,6,rep,name=recipients,proto3" json:"recipients,omitempty"`
	Attachments   []*Attachment          `protobuf:"bytes,7,rep,name=attachments,proto3" json:"attachments,omitempty"`
	GlobalFields  map[string]string      `protobuf:"bytes,8,rep,name=global_fields,json=globalFields,proto3" json:"global_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendHTMLReq) Reset() {
	*x = SendHTMLReq{}
	mi := &file_kannon_mailer_apiv1_mailerapiv1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendHTMLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendHTMLReq) ProtoMessage() {}

func (x *SendHTMLReq) ProtoReflect() protoreflect.Message {
	mi := &file_kannon_mailer_apiv1_mailerapiv1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendHTMLReq.ProtoReflect.Descriptor instead.
func (*SendHTMLReq) Descriptor() ([]byte, []int) {
	return file_kannon_mailer_apiv1_mailerapiv1_proto_rawDescGZIP(), []int{1}
}

func (x *SendHTMLReq) GetSender() *types.Sender {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *SendHTMLReq) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendHTMLReq) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *SendHTMLReq) GetScheduledTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledTime
	}
	return nil
}

func (x *SendHTMLReq) GetRecipients() []*types.Recipient {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *SendHTMLReq) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *SendHTMLReq) GetGlobalFields() map[string]string {
	if x != nil {
		return x.GlobalFields
	}
	return nil
}

type SendTemplateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        *types.Sender          `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	TemplateId    string                 `protobuf:"bytes,4,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	ScheduledTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=scheduled_time,json=scheduledTime,proto3,oneof" json:"scheduled_time,omitempty"`
	Recipients    []*types.Recipient     `protobuf:"bytes,6,rep,name=recipients,proto3" json:"recipients,omitempty"`
	Attachments   []*Attachment          `protobuf:"bytes,7,rep,name=attachments,proto3" json:"attachments,omitempty"`
	GlobalFields  map[string]string      `protobuf:"bytes,8,rep,name=global_fields,json=globalFields,proto3" json:"global_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTemplateReq) Reset() {
	*x = SendTemplateReq{}
	mi := &file_kannon_mailer_apiv1_mailerapiv1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTemplateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTemplateReq) ProtoMessage() {}

func (x *SendTemplateReq) ProtoReflect() protoreflect.Message {
	mi := &file_kannon_mailer_apiv1_mailerapiv1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTemplateReq.ProtoReflect.Descriptor instead.
func (*SendTemplateReq) Descriptor() ([]byte, []int) {
	return file_kannon_mailer_apiv1_mailerapiv1_proto_rawDescGZIP(), []int{2}
}

func (x *SendTemplateReq) GetSender() *types.Sender {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *SendTemplateReq) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendTemplateReq) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SendTemplateReq) GetScheduledTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledTime
	}
	return nil
}

func (x *SendTemplateReq) GetRecipients() []*types.Recipient {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *SendTemplateReq) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *SendTemplateReq) GetGlobalFields() map[string]string {
	if x != nil {
		return x.GlobalFields
	}
	return nil
}

type SendRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	ScheduledTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRes) Reset() {
	*x = SendRes{}
	mi := &file_kannon_mailer_apiv1_mailerapiv1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRes) ProtoMessage() {}

func (x *SendRes) ProtoReflect() protoreflect.Message {
	mi := &file_kannon_mailer_apiv1_mailerapiv1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRes.ProtoReflect.Descriptor instead.
func (*SendRes) Descriptor() ([]byte, []int) {
	return file_kannon_mailer_apiv1_mailerapiv1_proto_rawDescGZIP(), []int{3}
}

func (x *SendRes) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendRes) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SendRes) GetScheduledTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledTime
	}
	return nil
}

var File_kannon_mailer_apiv1_mailerapiv1_proto protoreflect.FileDescriptor

const file_kannon_mailer_apiv1_mailerapiv1_proto_rawDesc = "" +
	"\n" +
	"%kannon/mailer/apiv1/mailerapiv1.proto\x12\x17pkg.kannon.mailer.apiv1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ekannon/mailer/types/send.proto\"B\n" +
	"\n" +
	"Attachment\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"\xf8\x03\n" +
	"\vSendHTMLReq\x127\n" +
	"\x06sender\x18\x01 \x01(\v2\x1f.pkg.kannon.mailer.types.SenderR\x06sender\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x12\n" +
	"\x04html\x18\x04 \x01(\tR\x04html\x12F\n" +
	"\x0escheduled_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\rscheduledTime\x88\x01\x01\x12B\n" +
	"\n" +
	"recipients\x18\x06 \x03(\v2\".pkg.kannon.mailer.types.RecipientR\n" +
	"recipients\x12E\n" +
	"\vattachments\x18\a \x03(\v2#.pkg.kannon.mailer.apiv1.AttachmentR\vattachments\x12[\n" +
	"\rglobal_fields\x18\b \x03(\v26.pkg.kannon.mailer.apiv1.SendHTMLReq.GlobalFieldsEntryR\fglobalFields\x1a?\n" +
	"\x11GlobalFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x11\n" +
	"\x0f_scheduled_time\"\x8d\x04\n" +
	"\x0fSendTemplateReq\x127\n" +
	"\x06sender\x18\x01 \x01(\v2\x1f.pkg.kannon.mailer.types.SenderR\x06sender\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x1f\n" +
	"\vtemplate_id\x18\x04 \x01(\tR\n" +
	"templateId\x12F\n" +
	"\x0escheduled_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\rscheduledTime\x88\x01\x01\x12B\n" +
	"\n" +
	"recipients\x18\x06 \x03(\v2\".pkg.kannon.mailer.types.RecipientR\n" +
	"recipients\x12E\n" +
	"\vattachments\x18\a \x03(\v2#.pkg.kannon.mailer.apiv1.AttachmentR\vattachments\x12_\n" +
	"\rglobal_fields\x18\b \x03(\v2:.pkg.kannon.mailer.apiv1.SendTemplateReq.GlobalFieldsEntryR\fglobalFields\x1a?\n" +
	"\x11GlobalFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x11\n" +
	"\x0f_scheduled_time\"\x8c\x01\n" +
	"\aSendRes\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12A\n" +
	"\x0escheduled_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rscheduledTime2\xbc\x01\n" +
	"\x06Mailer\x12T\n" +
	"\bSendHTML\x12$.pkg.kannon.mailer.apiv1.SendHTMLReq\x1a .pkg.kannon.mailer.apiv1.SendRes\"\x00\x12\\\n" +
	"\fSendTemplate\x12(.pkg.kannon.mailer.apiv1.SendTemplateReq\x1a .pkg.kannon.mailer.apiv1.SendRes\"\x00B\xe9\x01\n" +
	"\x1bcom.pkg.kannon.mailer.apiv1B\x10Mailerapiv1ProtoP\x01Z8github.com/kannon-email/kannon/proto/kannon/mailer/apiv1\xa2\x02\x04PKMA\xaa\x02\x17Pkg.Kannon.Mailer.Apiv1\xca\x02\x17Pkg\\Kannon\\Mailer\\Apiv1\xe2\x02#Pkg\\Kannon\\Mailer\\Apiv1\\GPBMetadata\xea\x02\x1aPkg::Kannon::Mailer::Apiv1b\x06proto3"

var (
	file_kannon_mailer_apiv1_mailerapiv1_proto_rawDescOnce sync.Once
	file_kannon_mailer_apiv1_mailerapiv1_proto_rawDescData []byte
)

func file_kannon_mailer_apiv1_mailerapiv1_proto_rawDescGZIP() []byte {
	file_kannon_mailer_apiv1_mailerapiv1_proto_rawDescOnce.Do(func() {
		file_kannon_mailer_apiv1_mailerapiv1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kannon_mailer_apiv1_mailerapiv1_proto_rawDesc), len(file_kannon_mailer_apiv1_mailerapiv1_proto_rawDesc)))
	})
	return file_kannon_mailer_apiv1_mailerapiv1_proto_rawDescData
}

var file_kannon_mailer_apiv1_mailerapiv1_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_kannon_mailer_apiv1_mailerapiv1_proto_goTypes = []any{
	(*Attachment)(nil),            // 0: pkg.kannon.mailer.apiv1.Attachment
	(*SendHTMLReq)(nil),           // 1: pkg.kannon.mailer.apiv1.SendHTMLReq
	(*SendTemplateReq)(nil),       // 2: pkg.kannon.mailer.apiv1.SendTemplateReq
	(*SendRes)(nil),               // 3: pkg.kannon.mailer.apiv1.SendRes
	nil,                           // 4: pkg.kannon.mailer.apiv1.SendHTMLReq.GlobalFieldsEntry
	nil,                           // 5: pkg.kannon.mailer.apiv1.SendTemplateReq.GlobalFieldsEntry
	(*types.Sender)(nil),          // 6: pkg.kannon.mailer.types.Sender
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*types.Recipient)(nil),       // 8: pkg.kannon.mailer.types.Recipient
}
var file_kannon_mailer_apiv1_mailerapiv1_proto_depIdxs = []int32{
	6,  // 0: pkg.kannon.mailer.apiv1.SendHTMLReq.sender:type_name -> pkg.kannon.mailer.types.Sender
	7,  // 1: pkg.kannon.mailer.apiv1.SendHTMLReq.scheduled_time:type_name -> google.protobuf.Timestamp
	8,  // 2: pkg.kannon.mailer.apiv1.SendHTMLReq.recipients:type_name -> pkg.kannon.mailer.types.Recipient
	0,  // 3: pkg.kannon.mailer.apiv1.SendHTMLReq.attachments:type_name -> pkg.kannon.mailer.apiv1.Attachment
	4,  // 4: pkg.kannon.mailer.apiv1.SendHTMLReq.global_fields:type_name -> pkg.kannon.mailer.apiv1.SendHTMLReq.GlobalFieldsEntry
	6,  // 5: pkg.kannon.mailer.apiv1.SendTemplateReq.sender:type_name -> pkg.kannon.mailer.types.Sender
	7,  // 6: pkg.kannon.mailer.apiv1.SendTemplateReq.scheduled_time:type_name -> google.protobuf.Timestamp
	8,  // 7: pkg.kannon.mailer.apiv1.SendTemplateReq.recipients:type_name -> pkg.kannon.mailer.types.Recipient
	0,  // 8: pkg.kannon.mailer.apiv1.SendTemplateReq.attachments:type_name -> pkg.kannon.mailer.apiv1.Attachment
	5,  // 9: pkg.kannon.mailer.apiv1.SendTemplateReq.global_fields:type_name -> pkg.kannon.mailer.apiv1.SendTemplateReq.GlobalFieldsEntry
	7,  // 10: pkg.kannon.mailer.apiv1.SendRes.scheduled_time:type_name -> google.protobuf.Timestamp
	1,  // 11: pkg.kannon.mailer.apiv1.Mailer.SendHTML:input_type -> pkg.kannon.mailer.apiv1.SendHTMLReq
	2,  // 12: pkg.kannon.mailer.apiv1.Mailer.SendTemplate:input_type -> pkg.kannon.mailer.apiv1.SendTemplateReq
	3,  // 13: pkg.kannon.mailer.apiv1.Mailer.SendHTML:output_type -> pkg.kannon.mailer.apiv1.SendRes
	3,  // 14: pkg.kannon.mailer.apiv1.Mailer.SendTemplate:output_type -> pkg.kannon.mailer.apiv1.SendRes
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_kannon_mailer_apiv1_mailerapiv1_proto_init() }
func file_kannon_mailer_apiv1_mailerapiv1_proto_init() {
	if File_kannon_mailer_apiv1_mailerapiv1_proto != nil {
		return
	}
	file_kannon_mailer_apiv1_mailerapiv1_proto_msgTypes[1].OneofWrappers = []any{}
	file_kannon_mailer_apiv1_mailerapiv1_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kannon_mailer_apiv1_mailerapiv1_proto_rawDesc), len(file_kannon_mailer_apiv1_mailerapiv1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kannon_mailer_apiv1_mailerapiv1_proto_goTypes,
		DependencyIndexes: file_kannon_mailer_apiv1_mailerapiv1_proto_depIdxs,
		MessageInfos:      file_kannon_mailer_apiv1_mailerapiv1_proto_msgTypes,
	}.Build()
	File_kannon_mailer_apiv1_mailerapiv1_proto = out.File
	file_kannon_mailer_apiv1_mailerapiv1_proto_goTypes = nil
	file_kannon_mailer_apiv1_mailerapiv1_proto_depIdxs = nil
}
