// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isStatsData_Data is an autogenerated mock type for the isStatsData_Data type
type isStatsData_Data struct {
	mock.Mock
}

type isStatsData_Data_Expecter struct {
	mock *mock.Mock
}

func (_m *isStatsData_Data) EXPECT() *isStatsData_Data_Expecter {
	return &isStatsData_Data_Expecter{mock: &_m.Mock}
}

// isStatsData_Data provides a mock function with given fields:
func (_m *isStatsData_Data) isStatsData_Data() {
	_m.Called()
}

// isStatsData_Data_isStatsData_Data_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isStatsData_Data'
type isStatsData_Data_isStatsData_Data_Call struct {
	*mock.Call
}

// isStatsData_Data is a helper method to define mock.On call
func (_e *isStatsData_Data_Expecter) isStatsData_Data() *isStatsData_Data_isStatsData_Data_Call {
	return &isStatsData_Data_isStatsData_Data_Call{Call: _e.mock.On("isStatsData_Data")}
}

func (_c *isStatsData_Data_isStatsData_Data_Call) Run(run func()) *isStatsData_Data_isStatsData_Data_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *isStatsData_Data_isStatsData_Data_Call) Return() *isStatsData_Data_isStatsData_Data_Call {
	_c.Call.Return()
	return _c
}

type mockConstructorTestingTnewIsStatsData_Data interface {
	mock.TestingT
	Cleanup(func())
}

// newIsStatsData_Data creates a new instance of isStatsData_Data. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newIsStatsData_Data(t mockConstructorTestingTnewIsStatsData_Data) *isStatsData_Data {
	mock := &isStatsData_Data{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
