// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// loopFunc is an autogenerated mock type for the loopFunc type
type loopFunc struct {
	mock.Mock
}

type loopFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *loopFunc) EXPECT() *loopFunc_Expecter {
	return &loopFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *loopFunc) Execute(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// loopFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type loopFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *loopFunc_Expecter) Execute(_a0 interface{}) *loopFunc_Execute_Call {
	return &loopFunc_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *loopFunc_Execute_Call) Run(run func(_a0 context.Context)) *loopFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *loopFunc_Execute_Call) Return(_a0 error) *loopFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTnewLoopFunc interface {
	mock.TestingT
	Cleanup(func())
}

// newLoopFunc creates a new instance of loopFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newLoopFunc(t mockConstructorTestingTnewLoopFunc) *loopFunc {
	mock := &loopFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
