// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	apiv1 "github.com/ludusrusso/kannon/proto/kannon/mailer/apiv1"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// MailerClient is an autogenerated mock type for the MailerClient type
type MailerClient struct {
	mock.Mock
}

type MailerClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MailerClient) EXPECT() *MailerClient_Expecter {
	return &MailerClient_Expecter{mock: &_m.Mock}
}

// SendHTML provides a mock function with given fields: ctx, in, opts
func (_m *MailerClient) SendHTML(ctx context.Context, in *apiv1.SendHTMLReq, opts ...grpc.CallOption) (*apiv1.SendRes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *apiv1.SendRes
	if rf, ok := ret.Get(0).(func(context.Context, *apiv1.SendHTMLReq, ...grpc.CallOption) *apiv1.SendRes); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.SendRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *apiv1.SendHTMLReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MailerClient_SendHTML_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHTML'
type MailerClient_SendHTML_Call struct {
	*mock.Call
}

// SendHTML is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apiv1.SendHTMLReq
//   - opts ...grpc.CallOption
func (_e *MailerClient_Expecter) SendHTML(ctx interface{}, in interface{}, opts ...interface{}) *MailerClient_SendHTML_Call {
	return &MailerClient_SendHTML_Call{Call: _e.mock.On("SendHTML",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MailerClient_SendHTML_Call) Run(run func(ctx context.Context, in *apiv1.SendHTMLReq, opts ...grpc.CallOption)) *MailerClient_SendHTML_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apiv1.SendHTMLReq), variadicArgs...)
	})
	return _c
}

func (_c *MailerClient_SendHTML_Call) Return(_a0 *apiv1.SendRes, _a1 error) *MailerClient_SendHTML_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SendTemplate provides a mock function with given fields: ctx, in, opts
func (_m *MailerClient) SendTemplate(ctx context.Context, in *apiv1.SendTemplateReq, opts ...grpc.CallOption) (*apiv1.SendRes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *apiv1.SendRes
	if rf, ok := ret.Get(0).(func(context.Context, *apiv1.SendTemplateReq, ...grpc.CallOption) *apiv1.SendRes); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.SendRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *apiv1.SendTemplateReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MailerClient_SendTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTemplate'
type MailerClient_SendTemplate_Call struct {
	*mock.Call
}

// SendTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - in *apiv1.SendTemplateReq
//   - opts ...grpc.CallOption
func (_e *MailerClient_Expecter) SendTemplate(ctx interface{}, in interface{}, opts ...interface{}) *MailerClient_SendTemplate_Call {
	return &MailerClient_SendTemplate_Call{Call: _e.mock.On("SendTemplate",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MailerClient_SendTemplate_Call) Run(run func(ctx context.Context, in *apiv1.SendTemplateReq, opts ...grpc.CallOption)) *MailerClient_SendTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apiv1.SendTemplateReq), variadicArgs...)
	})
	return _c
}

func (_c *MailerClient_SendTemplate_Call) Return(_a0 *apiv1.SendRes, _a1 error) *MailerClient_SendTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewMailerClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewMailerClient creates a new instance of MailerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMailerClient(t mockConstructorTestingTNewMailerClient) *MailerClient {
	mock := &MailerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
