// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PurgeFunc is an autogenerated mock type for the PurgeFunc type
type PurgeFunc struct {
	mock.Mock
}

type PurgeFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *PurgeFunc) EXPECT() *PurgeFunc_Expecter {
	return &PurgeFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields:
func (_m *PurgeFunc) Execute() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PurgeFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type PurgeFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *PurgeFunc_Expecter) Execute() *PurgeFunc_Execute_Call {
	return &PurgeFunc_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *PurgeFunc_Execute_Call) Run(run func()) *PurgeFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PurgeFunc_Execute_Call) Return(_a0 error) *PurgeFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewPurgeFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewPurgeFunc creates a new instance of PurgeFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPurgeFunc(t mockConstructorTestingTNewPurgeFunc) *PurgeFunc {
	mock := &PurgeFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
