// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	pool "github.com/ludusrusso/kannon/internal/pool"
	mock "github.com/stretchr/testify/mock"

	sqlc "github.com/ludusrusso/kannon/internal/db"

	time "time"

	types "github.com/ludusrusso/kannon/proto/kannon/mailer/types"
)

// SendingPoolManager is an autogenerated mock type for the SendingPoolManager type
type SendingPoolManager struct {
	mock.Mock
}

type SendingPoolManager_Expecter struct {
	mock *mock.Mock
}

func (_m *SendingPoolManager) EXPECT() *SendingPoolManager_Expecter {
	return &SendingPoolManager_Expecter{mock: &_m.Mock}
}

// AddRecipientsPool provides a mock function with given fields: ctx, template, recipents, from, scheduled, subject, domain
func (_m *SendingPoolManager) AddRecipientsPool(ctx context.Context, template sqlc.Template, recipents []*types.Recipient, from pool.Sender, scheduled time.Time, subject string, domain string) (sqlc.Message, error) {
	ret := _m.Called(ctx, template, recipents, from, scheduled, subject, domain)

	var r0 sqlc.Message
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.Template, []*types.Recipient, pool.Sender, time.Time, string, string) sqlc.Message); ok {
		r0 = rf(ctx, template, recipents, from, scheduled, subject, domain)
	} else {
		r0 = ret.Get(0).(sqlc.Message)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, sqlc.Template, []*types.Recipient, pool.Sender, time.Time, string, string) error); ok {
		r1 = rf(ctx, template, recipents, from, scheduled, subject, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendingPoolManager_AddRecipientsPool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRecipientsPool'
type SendingPoolManager_AddRecipientsPool_Call struct {
	*mock.Call
}

// AddRecipientsPool is a helper method to define mock.On call
//   - ctx context.Context
//   - template sqlc.Template
//   - recipents []*types.Recipient
//   - from pool.Sender
//   - scheduled time.Time
//   - subject string
//   - domain string
func (_e *SendingPoolManager_Expecter) AddRecipientsPool(ctx interface{}, template interface{}, recipents interface{}, from interface{}, scheduled interface{}, subject interface{}, domain interface{}) *SendingPoolManager_AddRecipientsPool_Call {
	return &SendingPoolManager_AddRecipientsPool_Call{Call: _e.mock.On("AddRecipientsPool", ctx, template, recipents, from, scheduled, subject, domain)}
}

func (_c *SendingPoolManager_AddRecipientsPool_Call) Run(run func(ctx context.Context, template sqlc.Template, recipents []*types.Recipient, from pool.Sender, scheduled time.Time, subject string, domain string)) *SendingPoolManager_AddRecipientsPool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlc.Template), args[2].([]*types.Recipient), args[3].(pool.Sender), args[4].(time.Time), args[5].(string), args[6].(string))
	})
	return _c
}

func (_c *SendingPoolManager_AddRecipientsPool_Call) Return(_a0 sqlc.Message, _a1 error) *SendingPoolManager_AddRecipientsPool_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetToVerify provides a mock function with given fields: ctx, max
func (_m *SendingPoolManager) GetToVerify(ctx context.Context, max uint) ([]sqlc.SendingPoolEmail, error) {
	ret := _m.Called(ctx, max)

	var r0 []sqlc.SendingPoolEmail
	if rf, ok := ret.Get(0).(func(context.Context, uint) []sqlc.SendingPoolEmail); ok {
		r0 = rf(ctx, max)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.SendingPoolEmail)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, max)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendingPoolManager_GetToVerify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToVerify'
type SendingPoolManager_GetToVerify_Call struct {
	*mock.Call
}

// GetToVerify is a helper method to define mock.On call
//   - ctx context.Context
//   - max uint
func (_e *SendingPoolManager_Expecter) GetToVerify(ctx interface{}, max interface{}) *SendingPoolManager_GetToVerify_Call {
	return &SendingPoolManager_GetToVerify_Call{Call: _e.mock.On("GetToVerify", ctx, max)}
}

func (_c *SendingPoolManager_GetToVerify_Call) Run(run func(ctx context.Context, max uint)) *SendingPoolManager_GetToVerify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *SendingPoolManager_GetToVerify_Call) Return(_a0 []sqlc.SendingPoolEmail, _a1 error) *SendingPoolManager_GetToVerify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// PrepareForSend provides a mock function with given fields: ctx, max
func (_m *SendingPoolManager) PrepareForSend(ctx context.Context, max uint) ([]sqlc.SendingPoolEmail, error) {
	ret := _m.Called(ctx, max)

	var r0 []sqlc.SendingPoolEmail
	if rf, ok := ret.Get(0).(func(context.Context, uint) []sqlc.SendingPoolEmail); ok {
		r0 = rf(ctx, max)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.SendingPoolEmail)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, max)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendingPoolManager_PrepareForSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareForSend'
type SendingPoolManager_PrepareForSend_Call struct {
	*mock.Call
}

// PrepareForSend is a helper method to define mock.On call
//   - ctx context.Context
//   - max uint
func (_e *SendingPoolManager_Expecter) PrepareForSend(ctx interface{}, max interface{}) *SendingPoolManager_PrepareForSend_Call {
	return &SendingPoolManager_PrepareForSend_Call{Call: _e.mock.On("PrepareForSend", ctx, max)}
}

func (_c *SendingPoolManager_PrepareForSend_Call) Run(run func(ctx context.Context, max uint)) *SendingPoolManager_PrepareForSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *SendingPoolManager_PrepareForSend_Call) Return(_a0 []sqlc.SendingPoolEmail, _a1 error) *SendingPoolManager_PrepareForSend_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SetDelivered provides a mock function with given fields: ctx, messageID, email
func (_m *SendingPoolManager) SetDelivered(ctx context.Context, messageID string, email string) error {
	ret := _m.Called(ctx, messageID, email)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, messageID, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendingPoolManager_SetDelivered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDelivered'
type SendingPoolManager_SetDelivered_Call struct {
	*mock.Call
}

// SetDelivered is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID string
//   - email string
func (_e *SendingPoolManager_Expecter) SetDelivered(ctx interface{}, messageID interface{}, email interface{}) *SendingPoolManager_SetDelivered_Call {
	return &SendingPoolManager_SetDelivered_Call{Call: _e.mock.On("SetDelivered", ctx, messageID, email)}
}

func (_c *SendingPoolManager_SetDelivered_Call) Run(run func(ctx context.Context, messageID string, email string)) *SendingPoolManager_SetDelivered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *SendingPoolManager_SetDelivered_Call) Return(_a0 error) *SendingPoolManager_SetDelivered_Call {
	_c.Call.Return(_a0)
	return _c
}

// SetError provides a mock function with given fields: ctx, messageID, email, errMsg
func (_m *SendingPoolManager) SetError(ctx context.Context, messageID string, email string, errMsg string) error {
	ret := _m.Called(ctx, messageID, email, errMsg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, messageID, email, errMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendingPoolManager_SetError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetError'
type SendingPoolManager_SetError_Call struct {
	*mock.Call
}

// SetError is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID string
//   - email string
//   - errMsg string
func (_e *SendingPoolManager_Expecter) SetError(ctx interface{}, messageID interface{}, email interface{}, errMsg interface{}) *SendingPoolManager_SetError_Call {
	return &SendingPoolManager_SetError_Call{Call: _e.mock.On("SetError", ctx, messageID, email, errMsg)}
}

func (_c *SendingPoolManager_SetError_Call) Run(run func(ctx context.Context, messageID string, email string, errMsg string)) *SendingPoolManager_SetError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *SendingPoolManager_SetError_Call) Return(_a0 error) *SendingPoolManager_SetError_Call {
	_c.Call.Return(_a0)
	return _c
}

// SetScheduled provides a mock function with given fields: ctx, messageID, email
func (_m *SendingPoolManager) SetScheduled(ctx context.Context, messageID string, email string) error {
	ret := _m.Called(ctx, messageID, email)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, messageID, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendingPoolManager_SetScheduled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetScheduled'
type SendingPoolManager_SetScheduled_Call struct {
	*mock.Call
}

// SetScheduled is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID string
//   - email string
func (_e *SendingPoolManager_Expecter) SetScheduled(ctx interface{}, messageID interface{}, email interface{}) *SendingPoolManager_SetScheduled_Call {
	return &SendingPoolManager_SetScheduled_Call{Call: _e.mock.On("SetScheduled", ctx, messageID, email)}
}

func (_c *SendingPoolManager_SetScheduled_Call) Run(run func(ctx context.Context, messageID string, email string)) *SendingPoolManager_SetScheduled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *SendingPoolManager_SetScheduled_Call) Return(_a0 error) *SendingPoolManager_SetScheduled_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewSendingPoolManager interface {
	mock.TestingT
	Cleanup(func())
}

// NewSendingPoolManager creates a new instance of SendingPoolManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSendingPoolManager(t mockConstructorTestingTNewSendingPoolManager) *SendingPoolManager {
	mock := &SendingPoolManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
