// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeStatsApiV1Server is an autogenerated mock type for the UnsafeStatsApiV1Server type
type UnsafeStatsApiV1Server struct {
	mock.Mock
}

type UnsafeStatsApiV1Server_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafeStatsApiV1Server) EXPECT() *UnsafeStatsApiV1Server_Expecter {
	return &UnsafeStatsApiV1Server_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedStatsApiV1Server provides a mock function with given fields:
func (_m *UnsafeStatsApiV1Server) mustEmbedUnimplementedStatsApiV1Server() {
	_m.Called()
}

// UnsafeStatsApiV1Server_mustEmbedUnimplementedStatsApiV1Server_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedStatsApiV1Server'
type UnsafeStatsApiV1Server_mustEmbedUnimplementedStatsApiV1Server_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedStatsApiV1Server is a helper method to define mock.On call
func (_e *UnsafeStatsApiV1Server_Expecter) mustEmbedUnimplementedStatsApiV1Server() *UnsafeStatsApiV1Server_mustEmbedUnimplementedStatsApiV1Server_Call {
	return &UnsafeStatsApiV1Server_mustEmbedUnimplementedStatsApiV1Server_Call{Call: _e.mock.On("mustEmbedUnimplementedStatsApiV1Server")}
}

func (_c *UnsafeStatsApiV1Server_mustEmbedUnimplementedStatsApiV1Server_Call) Run(run func()) *UnsafeStatsApiV1Server_mustEmbedUnimplementedStatsApiV1Server_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafeStatsApiV1Server_mustEmbedUnimplementedStatsApiV1Server_Call) Return() *UnsafeStatsApiV1Server_mustEmbedUnimplementedStatsApiV1Server_Call {
	_c.Call.Return()
	return _c
}

type mockConstructorTestingTNewUnsafeStatsApiV1Server interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeStatsApiV1Server creates a new instance of UnsafeStatsApiV1Server. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeStatsApiV1Server(t mockConstructorTestingTNewUnsafeStatsApiV1Server) *UnsafeStatsApiV1Server {
	mock := &UnsafeStatsApiV1Server{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
