// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kannon/tracking/types/tracking.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TrackingMode is how much one engagement channel may be observed. The scale is
// ordered by increasing collection, but the rank order lives in Go rather than
// in these numbers, so a Mode can be inserted mid-scale without renumbering the
// wire.
type TrackingMode int32

const (
	// States nothing, and so imposes no restriction of its own.
	TrackingMode_TRACKING_MODE_UNSPECIFIED TrackingMode = 0
	// The channel is not observed at all.
	TrackingMode_TRACKING_MODE_OFF TrackingMode = 1
	// Counted in aggregate only; nothing retained that isolates one recipient.
	TrackingMode_TRACKING_MODE_ANONYMOUS TrackingMode = 2
	// Linkable within a single batch, carrying no recipient identity: events are
	// attributed to a pseudonym drawn afresh for every batch and stored nowhere.
	TrackingMode_TRACKING_MODE_PSEUDONYMOUS TrackingMode = 3
	// Attributed to the recipient.
	TrackingMode_TRACKING_MODE_IDENTIFIED TrackingMode = 4
	// Attributed, plus the IP address and user agent of the request.
	TrackingMode_TRACKING_MODE_FULL TrackingMode = 5
)

// Enum value maps for TrackingMode.
var (
	TrackingMode_name = map[int32]string{
		0: "TRACKING_MODE_UNSPECIFIED",
		1: "TRACKING_MODE_OFF",
		2: "TRACKING_MODE_ANONYMOUS",
		3: "TRACKING_MODE_PSEUDONYMOUS",
		4: "TRACKING_MODE_IDENTIFIED",
		5: "TRACKING_MODE_FULL",
	}
	TrackingMode_value = map[string]int32{
		"TRACKING_MODE_UNSPECIFIED":  0,
		"TRACKING_MODE_OFF":          1,
		"TRACKING_MODE_ANONYMOUS":    2,
		"TRACKING_MODE_PSEUDONYMOUS": 3,
		"TRACKING_MODE_IDENTIFIED":   4,
		"TRACKING_MODE_FULL":         5,
	}
)

func (x TrackingMode) Enum() *TrackingMode {
	p := new(TrackingMode)
	*p = x
	return p
}

func (x TrackingMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrackingMode) Descriptor() protoreflect.EnumDescriptor {
	return file_kannon_tracking_types_tracking_proto_enumTypes[0].Descriptor()
}

func (TrackingMode) Type() protoreflect.EnumType {
	return &file_kannon_tracking_types_tracking_proto_enumTypes[0]
}

func (x TrackingMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrackingMode.Descriptor instead.
func (TrackingMode) EnumDescriptor() ([]byte, []int) {
	return file_kannon_tracking_types_tracking_proto_rawDescGZIP(), []int{0}
}

// TrackingPolicy is a pair of TrackingModes, one governing opens and one
// governing links. Stated at domain, batch and recipient level, where a lower
// level may only restrict what the level above allows.
type TrackingPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Opens         TrackingMode           `protobuf:"varint,1,opt,name=opens,proto3,enum=pkg.kannon.tracking.types.TrackingMode" json:"opens,omitempty"`
	Links         TrackingMode           `protobuf:"varint,2,opt,name=links,proto3,enum=pkg.kannon.tracking.types.TrackingMode" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackingPolicy) Reset() {
	*x = TrackingPolicy{}
	mi := &file_kannon_tracking_types_tracking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackingPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackingPolicy) ProtoMessage() {}

func (x *TrackingPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_kannon_tracking_types_tracking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackingPolicy.ProtoReflect.Descriptor instead.
func (*TrackingPolicy) Descriptor() ([]byte, []int) {
	return file_kannon_tracking_types_tracking_proto_rawDescGZIP(), []int{0}
}

func (x *TrackingPolicy) GetOpens() TrackingMode {
	if x != nil {
		return x.Opens
	}
	return TrackingMode_TRACKING_MODE_UNSPECIFIED
}

func (x *TrackingPolicy) GetLinks() TrackingMode {
	if x != nil {
		return x.Links
	}
	return TrackingMode_TRACKING_MODE_UNSPECIFIED
}

var File_kannon_tracking_types_tracking_proto protoreflect.FileDescriptor

const file_kannon_tracking_types_tracking_proto_rawDesc = "" +
	"\n" +
	"$kannon/tracking/types/tracking.proto\x12\x19pkg.kannon.tracking.types\"\x8e\x01\n" +
	"\x0eTrackingPolicy\x12=\n" +
	"\x05opens\x18\x01 \x01(\x0e2'.pkg.kannon.tracking.types.TrackingModeR\x05opens\x12=\n" +
	"\x05links\x18\x02 \x01(\x0e2'.pkg.kannon.tracking.types.TrackingModeR\x05links*\xb7\x01\n" +
	"\fTrackingMode\x12\x1d\n" +
	"\x19TRACKING_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TRACKING_MODE_OFF\x10\x01\x12\x1b\n" +
	"\x17TRACKING_MODE_ANONYMOUS\x10\x02\x12\x1e\n" +
	"\x1aTRACKING_MODE_PSEUDONYMOUS\x10\x03\x12\x1c\n" +
	"\x18TRACKING_MODE_IDENTIFIED\x10\x04\x12\x16\n" +
	"\x12TRACKING_MODE_FULL\x10\x05B\xf2\x01\n" +
	"\x1dcom.pkg.kannon.tracking.typesB\rTrackingProtoP\x01Z:github.com/kannon-email/kannon/proto/kannon/tracking/types\xa2\x02\x04PKTT\xaa\x02\x19Pkg.Kannon.Tracking.Types\xca\x02\x19Pkg\\Kannon\\Tracking\\Types\xe2\x02%Pkg\\Kannon\\Tracking\\Types\\GPBMetadata\xea\x02\x1cPkg::Kannon::Tracking::Typesb\x06proto3"

var (
	file_kannon_tracking_types_tracking_proto_rawDescOnce sync.Once
	file_kannon_tracking_types_tracking_proto_rawDescData []byte
)

func file_kannon_tracking_types_tracking_proto_rawDescGZIP() []byte {
	file_kannon_tracking_types_tracking_proto_rawDescOnce.Do(func() {
		file_kannon_tracking_types_tracking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kannon_tracking_types_tracking_proto_rawDesc), len(file_kannon_tracking_types_tracking_proto_rawDesc)))
	})
	return file_kannon_tracking_types_tracking_proto_rawDescData
}

var file_kannon_tracking_types_tracking_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kannon_tracking_types_tracking_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kannon_tracking_types_tracking_proto_goTypes = []any{
	(TrackingMode)(0),      // 0: pkg.kannon.tracking.types.TrackingMode
	(*TrackingPolicy)(nil), // 1: pkg.kannon.tracking.types.TrackingPolicy
}
var file_kannon_tracking_types_tracking_proto_depIdxs = []int32{
	0, // 0: pkg.kannon.tracking.types.TrackingPolicy.opens:type_name -> pkg.kannon.tracking.types.TrackingMode
	0, // 1: pkg.kannon.tracking.types.TrackingPolicy.links:type_name -> pkg.kannon.tracking.types.TrackingMode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kannon_tracking_types_tracking_proto_init() }
func file_kannon_tracking_types_tracking_proto_init() {
	if File_kannon_tracking_types_tracking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kannon_tracking_types_tracking_proto_rawDesc), len(file_kannon_tracking_types_tracking_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kannon_tracking_types_tracking_proto_goTypes,
		DependencyIndexes: file_kannon_tracking_types_tracking_proto_depIdxs,
		EnumInfos:         file_kannon_tracking_types_tracking_proto_enumTypes,
		MessageInfos:      file_kannon_tracking_types_tracking_proto_msgTypes,
	}.Build()
	File_kannon_tracking_types_tracking_proto = out.File
	file_kannon_tracking_types_tracking_proto_goTypes = nil
	file_kannon_tracking_types_tracking_proto_depIdxs = nil
}
