// Package templates defines the Template domain entity per CONTEXT.md:
// the HTML/text body authored by a tenant and referenced from a Batch.
// The storage row is sqlc.Template; the on-the-wire payload is the proto
// Template; the domain entity is templates.Template.
//
// Template type values ("transient" / "template") are NOT renamed in this
// slice — the wire/DB-breaking rename to "persistent" is deferred per the
// PRD scope.
package templates

import (
	"errors"
	"fmt"
	"time"

	"github.com/kannon-email/kannon/internal/values"
	pb "github.com/kannon-email/kannon/proto/kannon/admin/apiv1"
	"github.com/nrednav/cuid2"
)

// Domain errors.
var (
	ErrTemplateNotFound = errors.New("template not found")
)

// Type is the lifecycle classification of a Template.
//
// A persistent template is authored once and reused across Batches; a
// transient template is generated by the Mailer API to capture the
// rendered HTML for a single Batch (e.g. SendHTML or a per-call
// global-fields override).
type Type string

const (
	// TypeTransient marks a template generated for a single send.
	TypeTransient Type = "transient"
	// TypePersistent marks a template authored by the tenant for reuse.
	// The DB enum value remains "template" — see package doc.
	TypePersistent Type = "template"
)

// Template is the domain entity for a tenant-authored email body.
type Template struct {
	templateID string
	html       string
	title      string
	domain     values.DomainName
	typ        Type
	createdAt  time.Time
	updatedAt  time.Time
}

// NewPersistent creates a new persistent Template with a freshly generated
// ID. createdAt/updatedAt are populated by the repository on Create.
//
// The Domain is not checked for emptiness: an values.DomainName can only come from
// values.Parse, which has already refused an empty or malformed one — and, since
// the id embeds it, refused the "@" and "/" that would make the id
// unparseable.
func NewPersistent(domain values.DomainName, html, title string) (*Template, error) {
	return &Template{
		templateID: newTemplateID(domain),
		html:       html,
		title:      title,
		domain:     domain,
		typ:        TypePersistent,
	}, nil
}

// NewTransient creates a new transient Template with a freshly generated ID.
func NewTransient(domain values.DomainName, html string) (*Template, error) {
	return &Template{
		templateID: newTemplateID(domain),
		html:       html,
		domain:     domain,
		typ:        TypeTransient,
	}, nil
}

// LoadParams contains all fields needed to rehydrate a Template from storage.
type LoadParams struct {
	TemplateID string
	Html       string
	Title      string
	Domain     values.DomainName
	Type       Type
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

// Load rehydrates a Template from stored data (used by repository implementations).
func Load(p LoadParams) *Template {
	return &Template{
		templateID: p.TemplateID,
		html:       p.Html,
		title:      p.Title,
		domain:     p.Domain,
		typ:        p.Type,
		createdAt:  p.CreatedAt,
		updatedAt:  p.UpdatedAt,
	}
}

// Getters

func (t *Template) TemplateID() string   { return t.templateID }
func (t *Template) Html() string         { return t.html }
func (t *Template) Title() string        { return t.title }
func (t *Template) Type() Type           { return t.typ }
func (t *Template) CreatedAt() time.Time { return t.createdAt }
func (t *Template) UpdatedAt() time.Time { return t.updatedAt }

// FQDN is the Domain this Template belongs to, in the form a Repository is
// addressed with. There is no string-rendering counterpart as there is on
// domains.Domain: a Template's Domain is never displayed — Pb omits it — and is
// only ever used to scope a lookup.
func (t *Template) DomainName() values.DomainName { return t.domain }

// Mutators

// SetHTML overwrites the rendered body. Used by Repository.Update.
func (t *Template) SetHTML(html string) { t.html = html }

// SetTitle overwrites the title. Used by Repository.Update.
func (t *Template) SetTitle(title string) { t.title = title }

// Pb translates to the proto wire type.
func (t *Template) Pb() *pb.Template {
	return &pb.Template{
		TemplateId: t.templateID,
		Html:       t.html,
		Title:      t.title,
		Type:       string(t.typ),
	}
}

// newTemplateID composes the id from the canonical FQDN. The "@" is the
// separator a later slice parses back out (issue #438), and it is sound only
// because values.Parse refuses an "@" inside an FQDN.
func newTemplateID(domain values.DomainName) string {
	return fmt.Sprintf("template_%v@%v", cuid2.Generate(), domain.String())
}
