// Package templates defines the Template domain entity per CONTEXT.md: the body authored by a
// tenant and referenced from a Batch. Storage row sqlc.Template, wire payload proto Template.
// The type values ("transient" / "template") are not renamed in this slice — PRD scope.
package templates

import (
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/kannon-email/kannon/internal/values"
	pb "github.com/kannon-email/kannon/proto/kannon/admin/apiv1"
	"github.com/nrednav/cuid2"
)

// Domain errors.
var (
	ErrTemplateNotFound = errors.New("template not found")
)

// Type is the lifecycle classification of a Template: a persistent one is authored once and
// reused across Batches, a transient one is generated by the Mailer API to capture the rendered
// HTML of a single Batch.
type Type string

const (
	// TypeTransient marks a template generated for a single send.
	TypeTransient Type = "transient"
	// TypePersistent marks a template authored by the tenant for reuse.
	// The DB enum value remains "template" — see package doc.
	TypePersistent Type = "template"
)

// Template is the domain entity for a tenant-authored email body.
type Template struct {
	templateID string
	html       string
	title      string
	domain     values.DomainName
	typ        Type
	createdAt  time.Time
	updatedAt  time.Time
}

// NewPersistent creates a new persistent Template with a freshly generated ID; createdAt and
// updatedAt are populated by the repository on Create. The Domain needs no check: a Name comes
// only from Parse, which has already refused the "@" and "/" that would break the id.
func NewPersistent(domain values.DomainName, html, title string) (*Template, error) {
	return &Template{
		templateID: newTemplateID(domain),
		html:       html,
		title:      title,
		domain:     domain,
		typ:        TypePersistent,
	}, nil
}

// NewTransient creates a new transient Template with a freshly generated ID.
func NewTransient(domain values.DomainName, html string) (*Template, error) {
	return &Template{
		templateID: newTemplateID(domain),
		html:       html,
		domain:     domain,
		typ:        TypeTransient,
	}, nil
}

// LoadParams contains all fields needed to rehydrate a Template from storage.
type LoadParams struct {
	TemplateID string
	Html       string
	Title      string
	Domain     values.DomainName
	Type       Type
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

// Load rehydrates a Template from stored data (used by repository implementations).
func Load(p LoadParams) *Template {
	return &Template{
		templateID: p.TemplateID,
		html:       p.Html,
		title:      p.Title,
		domain:     p.Domain,
		typ:        p.Type,
		createdAt:  p.CreatedAt,
		updatedAt:  p.UpdatedAt,
	}
}

func (t *Template) TemplateID() string   { return t.templateID }
func (t *Template) Html() string         { return t.html }
func (t *Template) Title() string        { return t.title }
func (t *Template) Type() Type           { return t.typ }
func (t *Template) CreatedAt() time.Time { return t.createdAt }
func (t *Template) UpdatedAt() time.Time { return t.updatedAt }

// DomainName is the Domain this Template belongs to, in the form a Repository is addressed with.
// No string-rendering counterpart as on domains.Domain: a Template's Domain is never displayed —
// Pb omits it — and is only ever used to scope a lookup.
func (t *Template) DomainName() values.DomainName { return t.domain }

// SetHTML overwrites the rendered body. Used by Repository.Update.
func (t *Template) SetHTML(html string) { t.html = html }

// SetTitle overwrites the title. Used by Repository.Update.
func (t *Template) SetTitle(title string) { t.title = title }

// Pb translates to the proto wire type.
func (t *Template) Pb() *pb.Template {
	return &pb.Template{
		TemplateId: t.templateID,
		Html:       t.html,
		Title:      t.title,
		Type:       string(t.typ),
	}
}

// newTemplateID composes the id from the canonical domain name. The "@" is the
// separator DomainFromID parses back out, and it is sound only because
// values.Parse refuses an "@" inside a domain name.
func newTemplateID(domain values.DomainName) string {
	return fmt.Sprintf("template_%v%v%v", cuid2.Generate(), idSeparator, domain.String())
}

// idSeparator divides a Template id's generated part from the Domain it belongs to. Named rather
// than written twice: it is the whole of DomainFromID's parse, and a literal in both the
// constructor and the parse is one somebody can change in only one of them.
const idSeparator = "@"

// DomainFromID recovers the Domain a Template id was composed from, for the three Admin API
// operations whose request carries only a template_id. Exactly one "@" is required, refusing the
// "x@a.com@b.com" ambiguity; authorizing on it is sound because the parse can only narrow (ADR 0008).
func DomainFromID(templateID string) (values.DomainName, error) {
	if n := strings.Count(templateID, idSeparator); n != 1 {
		return values.DomainName{}, fmt.Errorf("template id %q must contain exactly one %q, found %d", templateID, idSeparator, n)
	}

	_, raw, _ := strings.Cut(templateID, idSeparator)
	domain, err := values.Parse(raw)
	if err != nil {
		return values.DomainName{}, fmt.Errorf("template id %q carries no Domain: %w", templateID, err)
	}
	return domain, nil
}
