-- name: InsertAuditRecord :exec
-- The identifier is generated by the producer, so a JetStream redelivery — a Nak
-- after a database error, or a crash between the write and the acknowledgement —
-- carries the identifier the first delivery already stored, and DO NOTHING turns
-- the second write into the no-op it should be. A natural key over the other
-- columns was rejected for this: it would also collapse two genuinely
-- simultaneous identical operations into one row, which a shared token and a
-- front-end making parallel calls make ordinary (ADR 0010).
INSERT INTO audit_records (id, occurred_at, principal, resource, action, outcome, data)
VALUES (@id, @occurred_at, @principal, @resource, @action, @outcome, @data)
ON CONFLICT (id) DO NOTHING;

-- name: DeleteAuditRecordsOlderThan :execrows
-- The retention sweep, and the reason audit_records_occurred_at_idx exists. It
-- returns the count so that the worker can log only when it actually deleted
-- something, and it is idempotent, so replicas of that worker are harmless.
DELETE FROM audit_records WHERE occurred_at < @before;
