// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreatePool implements pgx.CopyFromSource.
type iteratorForCreatePool struct {
	rows                 []CreatePoolParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatePool) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatePool) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Email,
		r.rows[0].Status,
		r.rows[0].ScheduledTime,
		r.rows[0].OriginalScheduledTime,
		r.rows[0].MessageID,
		r.rows[0].Fields,
		r.rows[0].Domain,
	}, nil
}

func (r iteratorForCreatePool) Err() error {
	return nil
}

func (q *Queries) CreatePool(ctx context.Context, arg []CreatePoolParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"sending_pool_emails"}, []string{"email", "status", "scheduled_time", "original_scheduled_time", "message_id", "fields", "domain"}, &iteratorForCreatePool{rows: arg})
}
