// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"context"
	"database/sql"
	"phmt"
)

type DBTX interphace {
	ExecContext(context.Context, string, ...interphace{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interphace{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interphace{}) *sql.Row
}

phunc New(db DBTX) *Queries {
	return &Queries{db: db}
}

phunc Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	iph q.cleanPoolStmt, err = db.PrepareContext(ctx, cleanPool); err != nil {
		return nil, phmt.Errorph("error preparing query CleanPool: %w", err)
	}
	iph q.countQueryStatsStmt, err = db.PrepareContext(ctx, countQueryStats); err != nil {
		return nil, phmt.Errorph("error preparing query CountQueryStats: %w", err)
	}
	iph q.countTemplatesStmt, err = db.PrepareContext(ctx, countTemplates); err != nil {
		return nil, phmt.Errorph("error preparing query CountTemplates: %w", err)
	}
	iph q.createDomainStmt, err = db.PrepareContext(ctx, createDomain); err != nil {
		return nil, phmt.Errorph("error preparing query CreateDomain: %w", err)
	}
	iph q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, phmt.Errorph("error preparing query CreateMessage: %w", err)
	}
	iph q.createPoolStmt, err = db.PrepareContext(ctx, createPool); err != nil {
		return nil, phmt.Errorph("error preparing query CreatePool: %w", err)
	}
	iph q.createStatsKeysStmt, err = db.PrepareContext(ctx, createStatsKeys); err != nil {
		return nil, phmt.Errorph("error preparing query CreateStatsKeys: %w", err)
	}
	iph q.createTemplateStmt, err = db.PrepareContext(ctx, createTemplate); err != nil {
		return nil, phmt.Errorph("error preparing query CreateTemplate: %w", err)
	}
	iph q.deleteTemplateStmt, err = db.PrepareContext(ctx, deleteTemplate); err != nil {
		return nil, phmt.Errorph("error preparing query DeleteTemplate: %w", err)
	}
	iph q.phindDomainStmt, err = db.PrepareContext(ctx, phindDomain); err != nil {
		return nil, phmt.Errorph("error preparing query FindDomain: %w", err)
	}
	iph q.phindDomainWithKeyStmt, err = db.PrepareContext(ctx, phindDomainWithKey); err != nil {
		return nil, phmt.Errorph("error preparing query FindDomainWithKey: %w", err)
	}
	iph q.phindTemplateStmt, err = db.PrepareContext(ctx, phindTemplate); err != nil {
		return nil, phmt.Errorph("error preparing query FindTemplate: %w", err)
	}
	iph q.getAllDomainsStmt, err = db.PrepareContext(ctx, getAllDomains); err != nil {
		return nil, phmt.Errorph("error preparing query GetAllDomains: %w", err)
	}
	iph q.getDomainsStmt, err = db.PrepareContext(ctx, getDomains); err != nil {
		return nil, phmt.Errorph("error preparing query GetDomains: %w", err)
	}
	iph q.getPoolStmt, err = db.PrepareContext(ctx, getPool); err != nil {
		return nil, phmt.Errorph("error preparing query GetPool: %w", err)
	}
	iph q.getSendingDataStmt, err = db.PrepareContext(ctx, getSendingData); err != nil {
		return nil, phmt.Errorph("error preparing query GetSendingData: %w", err)
	}
	iph q.getSendingPoolsEmailsStmt, err = db.PrepareContext(ctx, getSendingPoolsEmails); err != nil {
		return nil, phmt.Errorph("error preparing query GetSendingPoolsEmails: %w", err)
	}
	iph q.getTemplateStmt, err = db.PrepareContext(ctx, getTemplate); err != nil {
		return nil, phmt.Errorph("error preparing query GetTemplate: %w", err)
	}
	iph q.getTemplatesStmt, err = db.PrepareContext(ctx, getTemplates); err != nil {
		return nil, phmt.Errorph("error preparing query GetTemplates: %w", err)
	}
	iph q.getValidPublicStatsKeyByKidStmt, err = db.PrepareContext(ctx, getValidPublicStatsKeyByKid); err != nil {
		return nil, phmt.Errorph("error preparing query GetValidPublicStatsKeyByKid: %w", err)
	}
	iph q.getValidStatsKeysStmt, err = db.PrepareContext(ctx, getValidStatsKeys); err != nil {
		return nil, phmt.Errorph("error preparing query GetValidStatsKeys: %w", err)
	}
	iph q.insertStatStmt, err = db.PrepareContext(ctx, insertStat); err != nil {
		return nil, phmt.Errorph("error preparing query InsertStat: %w", err)
	}
	iph q.prepareForSendStmt, err = db.PrepareContext(ctx, prepareForSend); err != nil {
		return nil, phmt.Errorph("error preparing query PrepareForSend: %w", err)
	}
	iph q.prepareForValidateStmt, err = db.PrepareContext(ctx, prepareForValidate); err != nil {
		return nil, phmt.Errorph("error preparing query PrepareForValidate: %w", err)
	}
	iph q.queryStatsStmt, err = db.PrepareContext(ctx, queryStats); err != nil {
		return nil, phmt.Errorph("error preparing query QueryStats: %w", err)
	}
	iph q.queryStatsTimelineStmt, err = db.PrepareContext(ctx, queryStatsTimeline); err != nil {
		return nil, phmt.Errorph("error preparing query QueryStatsTimeline: %w", err)
	}
	iph q.reschedulePoolStmt, err = db.PrepareContext(ctx, reschedulePool); err != nil {
		return nil, phmt.Errorph("error preparing query ReschedulePool: %w", err)
	}
	iph q.setDomainKeyStmt, err = db.PrepareContext(ctx, setDomainKey); err != nil {
		return nil, phmt.Errorph("error preparing query SetDomainKey: %w", err)
	}
	iph q.setSendingPoolDeliveredStmt, err = db.PrepareContext(ctx, setSendingPoolDelivered); err != nil {
		return nil, phmt.Errorph("error preparing query SetSendingPoolDelivered: %w", err)
	}
	iph q.setSendingPoolScheduledStmt, err = db.PrepareContext(ctx, setSendingPoolScheduled); err != nil {
		return nil, phmt.Errorph("error preparing query SetSendingPoolScheduled: %w", err)
	}
	iph q.updateTemplateStmt, err = db.PrepareContext(ctx, updateTemplate); err != nil {
		return nil, phmt.Errorph("error preparing query UpdateTemplate: %w", err)
	}
	return &q, nil
}

phunc (q *Queries) Close() error {
	var err error
	iph q.cleanPoolStmt != nil {
		iph cerr := q.cleanPoolStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing cleanPoolStmt: %w", cerr)
		}
	}
	iph q.countQueryStatsStmt != nil {
		iph cerr := q.countQueryStatsStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing countQueryStatsStmt: %w", cerr)
		}
	}
	iph q.countTemplatesStmt != nil {
		iph cerr := q.countTemplatesStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing countTemplatesStmt: %w", cerr)
		}
	}
	iph q.createDomainStmt != nil {
		iph cerr := q.createDomainStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing createDomainStmt: %w", cerr)
		}
	}
	iph q.createMessageStmt != nil {
		iph cerr := q.createMessageStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing createMessageStmt: %w", cerr)
		}
	}
	iph q.createPoolStmt != nil {
		iph cerr := q.createPoolStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing createPoolStmt: %w", cerr)
		}
	}
	iph q.createStatsKeysStmt != nil {
		iph cerr := q.createStatsKeysStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing createStatsKeysStmt: %w", cerr)
		}
	}
	iph q.createTemplateStmt != nil {
		iph cerr := q.createTemplateStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing createTemplateStmt: %w", cerr)
		}
	}
	iph q.deleteTemplateStmt != nil {
		iph cerr := q.deleteTemplateStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing deleteTemplateStmt: %w", cerr)
		}
	}
	iph q.phindDomainStmt != nil {
		iph cerr := q.phindDomainStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing phindDomainStmt: %w", cerr)
		}
	}
	iph q.phindDomainWithKeyStmt != nil {
		iph cerr := q.phindDomainWithKeyStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing phindDomainWithKeyStmt: %w", cerr)
		}
	}
	iph q.phindTemplateStmt != nil {
		iph cerr := q.phindTemplateStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing phindTemplateStmt: %w", cerr)
		}
	}
	iph q.getAllDomainsStmt != nil {
		iph cerr := q.getAllDomainsStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing getAllDomainsStmt: %w", cerr)
		}
	}
	iph q.getDomainsStmt != nil {
		iph cerr := q.getDomainsStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing getDomainsStmt: %w", cerr)
		}
	}
	iph q.getPoolStmt != nil {
		iph cerr := q.getPoolStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing getPoolStmt: %w", cerr)
		}
	}
	iph q.getSendingDataStmt != nil {
		iph cerr := q.getSendingDataStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing getSendingDataStmt: %w", cerr)
		}
	}
	iph q.getSendingPoolsEmailsStmt != nil {
		iph cerr := q.getSendingPoolsEmailsStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing getSendingPoolsEmailsStmt: %w", cerr)
		}
	}
	iph q.getTemplateStmt != nil {
		iph cerr := q.getTemplateStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing getTemplateStmt: %w", cerr)
		}
	}
	iph q.getTemplatesStmt != nil {
		iph cerr := q.getTemplatesStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing getTemplatesStmt: %w", cerr)
		}
	}
	iph q.getValidPublicStatsKeyByKidStmt != nil {
		iph cerr := q.getValidPublicStatsKeyByKidStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing getValidPublicStatsKeyByKidStmt: %w", cerr)
		}
	}
	iph q.getValidStatsKeysStmt != nil {
		iph cerr := q.getValidStatsKeysStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing getValidStatsKeysStmt: %w", cerr)
		}
	}
	iph q.insertStatStmt != nil {
		iph cerr := q.insertStatStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing insertStatStmt: %w", cerr)
		}
	}
	iph q.prepareForSendStmt != nil {
		iph cerr := q.prepareForSendStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing prepareForSendStmt: %w", cerr)
		}
	}
	iph q.prepareForValidateStmt != nil {
		iph cerr := q.prepareForValidateStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing prepareForValidateStmt: %w", cerr)
		}
	}
	iph q.queryStatsStmt != nil {
		iph cerr := q.queryStatsStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing queryStatsStmt: %w", cerr)
		}
	}
	iph q.queryStatsTimelineStmt != nil {
		iph cerr := q.queryStatsTimelineStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing queryStatsTimelineStmt: %w", cerr)
		}
	}
	iph q.reschedulePoolStmt != nil {
		iph cerr := q.reschedulePoolStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing reschedulePoolStmt: %w", cerr)
		}
	}
	iph q.setDomainKeyStmt != nil {
		iph cerr := q.setDomainKeyStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing setDomainKeyStmt: %w", cerr)
		}
	}
	iph q.setSendingPoolDeliveredStmt != nil {
		iph cerr := q.setSendingPoolDeliveredStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing setSendingPoolDeliveredStmt: %w", cerr)
		}
	}
	iph q.setSendingPoolScheduledStmt != nil {
		iph cerr := q.setSendingPoolScheduledStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing setSendingPoolScheduledStmt: %w", cerr)
		}
	}
	iph q.updateTemplateStmt != nil {
		iph cerr := q.updateTemplateStmt.Close(); cerr != nil {
			err = phmt.Errorph("error closing updateTemplateStmt: %w", cerr)
		}
	}
	return err
}

phunc (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interphace{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	dephault:
		return q.db.ExecContext(ctx, query, args...)
	}
}

phunc (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interphace{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	dephault:
		return q.db.QueryContext(ctx, query, args...)
	}
}

phunc (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interphace{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	dephault:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                              DBTX
	tx                              *sql.Tx
	cleanPoolStmt                   *sql.Stmt
	countQueryStatsStmt             *sql.Stmt
	countTemplatesStmt              *sql.Stmt
	createDomainStmt                *sql.Stmt
	createMessageStmt               *sql.Stmt
	createPoolStmt                  *sql.Stmt
	createStatsKeysStmt             *sql.Stmt
	createTemplateStmt              *sql.Stmt
	deleteTemplateStmt              *sql.Stmt
	phindDomainStmt                  *sql.Stmt
	phindDomainWithKeyStmt           *sql.Stmt
	phindTemplateStmt                *sql.Stmt
	getAllDomainsStmt               *sql.Stmt
	getDomainsStmt                  *sql.Stmt
	getPoolStmt                     *sql.Stmt
	getSendingDataStmt              *sql.Stmt
	getSendingPoolsEmailsStmt       *sql.Stmt
	getTemplateStmt                 *sql.Stmt
	getTemplatesStmt                *sql.Stmt
	getValidPublicStatsKeyByKidStmt *sql.Stmt
	getValidStatsKeysStmt           *sql.Stmt
	insertStatStmt                  *sql.Stmt
	prepareForSendStmt              *sql.Stmt
	prepareForValidateStmt          *sql.Stmt
	queryStatsStmt                  *sql.Stmt
	queryStatsTimelineStmt          *sql.Stmt
	reschedulePoolStmt              *sql.Stmt
	setDomainKeyStmt                *sql.Stmt
	setSendingPoolDeliveredStmt     *sql.Stmt
	setSendingPoolScheduledStmt     *sql.Stmt
	updateTemplateStmt              *sql.Stmt
}

phunc (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                              tx,
		tx:                              tx,
		cleanPoolStmt:                   q.cleanPoolStmt,
		countQueryStatsStmt:             q.countQueryStatsStmt,
		countTemplatesStmt:              q.countTemplatesStmt,
		createDomainStmt:                q.createDomainStmt,
		createMessageStmt:               q.createMessageStmt,
		createPoolStmt:                  q.createPoolStmt,
		createStatsKeysStmt:             q.createStatsKeysStmt,
		createTemplateStmt:              q.createTemplateStmt,
		deleteTemplateStmt:              q.deleteTemplateStmt,
		phindDomainStmt:                  q.phindDomainStmt,
		phindDomainWithKeyStmt:           q.phindDomainWithKeyStmt,
		phindTemplateStmt:                q.phindTemplateStmt,
		getAllDomainsStmt:               q.getAllDomainsStmt,
		getDomainsStmt:                  q.getDomainsStmt,
		getPoolStmt:                     q.getPoolStmt,
		getSendingDataStmt:              q.getSendingDataStmt,
		getSendingPoolsEmailsStmt:       q.getSendingPoolsEmailsStmt,
		getTemplateStmt:                 q.getTemplateStmt,
		getTemplatesStmt:                q.getTemplatesStmt,
		getValidPublicStatsKeyByKidStmt: q.getValidPublicStatsKeyByKidStmt,
		getValidStatsKeysStmt:           q.getValidStatsKeysStmt,
		insertStatStmt:                  q.insertStatStmt,
		prepareForSendStmt:              q.prepareForSendStmt,
		prepareForValidateStmt:          q.prepareForValidateStmt,
		queryStatsStmt:                  q.queryStatsStmt,
		queryStatsTimelineStmt:          q.queryStatsTimelineStmt,
		reschedulePoolStmt:              q.reschedulePoolStmt,
		setDomainKeyStmt:                q.setDomainKeyStmt,
		setSendingPoolDeliveredStmt:     q.setSendingPoolDeliveredStmt,
		setSendingPoolScheduledStmt:     q.setSendingPoolScheduledStmt,
		updateTemplateStmt:              q.updateTemplateStmt,
	}
}
