// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: q.sql

package sqlc

import (
	"context"

	tracking "github.com/kannon-email/kannon/internal/tracking"
)

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains
    (domain, dkim_private_key, dkim_public_key)
    VALUES ($1, $2, $3)
    RETURNING id, domain, created_at, dkim_private_key, dkim_public_key, tracking
`

type CreateDomainParams struct {
	Domain         string
	DkimPrivateKey string
	DkimPublicKey  string
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, createDomain, arg.Domain, arg.DkimPrivateKey, arg.DkimPublicKey)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.CreatedAt,
		&i.DkimPrivateKey,
		&i.DkimPublicKey,
		&i.Tracking,
	)
	return i, err
}

const findDomain = `-- name: FindDomain :one
SELECT
    id, domain, created_at, dkim_private_key, dkim_public_key, tracking
FROM domains
    WHERE domain = $1
`

func (q *Queries) FindDomain(ctx context.Context, domain string) (Domain, error) {
	row := q.db.QueryRow(ctx, findDomain, domain)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.CreatedAt,
		&i.DkimPrivateKey,
		&i.DkimPublicKey,
		&i.Tracking,
	)
	return i, err
}

const findTemplate = `-- name: FindTemplate :one
SELECT id, template_id, html, domain, type, title, created_at, updated_at FROM templates
WHERE template_id = $1
AND domain = $2
`

type FindTemplateParams struct {
	TemplateID string
	Domain     string
}

func (q *Queries) FindTemplate(ctx context.Context, arg FindTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, findTemplate, arg.TemplateID, arg.Domain)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Html,
		&i.Domain,
		&i.Type,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllDomains = `-- name: GetAllDomains :many
SELECT
    id, domain, created_at, dkim_private_key, dkim_public_key, tracking
FROM domains
ORDER BY id
`

func (q *Queries) GetAllDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.Query(ctx, getAllDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.CreatedAt,
			&i.DkimPrivateKey,
			&i.DkimPublicKey,
			&i.Tracking,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDomains = `-- name: GetDomains :many
SELECT id, domain, created_at, dkim_private_key, dkim_public_key, tracking FROM domains ORDER BY id
`

func (q *Queries) GetDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.Query(ctx, getDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.CreatedAt,
			&i.DkimPrivateKey,
			&i.DkimPublicKey,
			&i.Tracking,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDomainTracking = `-- name: SetDomainTracking :one
UPDATE domains
    SET tracking = $2
    WHERE domain = $1
    RETURNING id, domain, created_at, dkim_private_key, dkim_public_key, tracking
`

type SetDomainTrackingParams struct {
	Domain   string
	Tracking tracking.Policy
}

func (q *Queries) SetDomainTracking(ctx context.Context, arg SetDomainTrackingParams) (Domain, error) {
	row := q.db.QueryRow(ctx, setDomainTracking, arg.Domain, arg.Tracking)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.CreatedAt,
		&i.DkimPrivateKey,
		&i.DkimPublicKey,
		&i.Tracking,
	)
	return i, err
}
