// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: templates.sql

package sqlc

import (
	"context"
)

const countTemplates = `-- name: CountTemplates :one
SELECT COUNT(*) FROM templates WHERE domain = $1 AND type = 'template'
`

func (q *Queries) CountTemplates(ctx context.Context, domain string) (int64, error) {
	row := q.queryRow(ctx, q.countTemplatesStmt, countTemplates, domain)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (template_id, html, title, domain, type)
    VALUES ($1, $2, $3, $4, $5)
    RETURNING id, template_id, html, domain, type, title, created_at, updated_at
`

type CreateTemplateParams struct {
	TemplateID string
	Html       string
	Title      string
	Domain     string
	Type       TemplateType
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.queryRow(ctx, q.createTemplateStmt, createTemplate,
		arg.TemplateID,
		arg.Html,
		arg.Title,
		arg.Domain,
		arg.Type,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Html,
		&i.Domain,
		&i.Type,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :one
DELETE FROM templates WHERE template_id = $1
    RETURNING id, template_id, html, domain, type, title, created_at, updated_at
`

func (q *Queries) DeleteTemplate(ctx context.Context, templateID string) (Template, error) {
	row := q.queryRow(ctx, q.deleteTemplateStmt, deleteTemplate, templateID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Html,
		&i.Domain,
		&i.Type,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, template_id, html, domain, type, title, created_at, updated_at FROM templates WHERE template_id = $1
`

func (q *Queries) GetTemplate(ctx context.Context, templateID string) (Template, error) {
	row := q.queryRow(ctx, q.getTemplateStmt, getTemplate, templateID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Html,
		&i.Domain,
		&i.Type,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplates = `-- name: GetTemplates :many
SELECT id, template_id, html, domain, type, title, created_at, updated_at FROM templates WHERE domain = $1 AND type = 'template' LIMIT $3 OFFSET $2
`

type GetTemplatesParams struct {
	Domain string
	Skip   int32
	Take   int32
}

func (q *Queries) GetTemplates(ctx context.Context, arg GetTemplatesParams) ([]Template, error) {
	rows, err := q.query(ctx, q.getTemplatesStmt, getTemplates, arg.Domain, arg.Skip, arg.Take)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Html,
			&i.Domain,
			&i.Type,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates SET
	html = $2,
	title = $3,
	updated_at = now()
WHERE template_id = $1
	RETURNING id, template_id, html, domain, type, title, created_at, updated_at
`

type UpdateTemplateParams struct {
	TemplateID string
	Html       string
	Title      string
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.queryRow(ctx, q.updateTemplateStmt, updateTemplate, arg.TemplateID, arg.Html, arg.Title)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Html,
		&i.Domain,
		&i.Type,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
